### ISSUE TITLE
Confusing aspects of Group admin guide

### ISSUE THREAD

**Issue by bhaugen** [open-app/holodex#70]
These might want to become separate issues, but I am plopping them together for now...
- As far as I can tell, https://github.com/holodex/enspiral-data does not have a roleTypes directory. Is one necessary? 
  - See also https://github.com/open-app/holodex/issues/63
- Is there a principle behind what is source and what is target in relationshipTypes? Examples:
  - set: source: subgroup, target: parent-group
  - membership: source: member, target: group
  - stewardship: source: steward, target: stewardee
  - Note: we have struggled with this issue, too. RelationshipTypes need to be very generic, so the names of the "ends" need to be generic as well, and generic names don't give much direction for implementors.
- What's the estimated timing on https://github.com/open-app/holodex/issues/69 ? 
  - Might affect whether I cheat and write YAML by hand or generate it programmatically.
- Do you guys intend to host a demo that could display other org data, or should we plan on running the holodex app ourselves (this is in the short term)?

**Comment by ahdinosaur** [comment]
- we don't have any standalone role types yet, so we put our role types within the relationship types
- there's no reason both sides can't be both source and target, which i reckon is true of parent / child and group / member relationships
- good question, i've warming up more and more to doing it, so this add more fuel to that fire. what's the tradeoff between writing by hand and generating programmatically? we could be keen to help y'all generate programmatically given a raw dump
- yes, we can host an instance for y'all

**Comment by bhaugen** [comment]
Thanks. Especially about the instance. Can you host an instance that different networks could plug into by means of a query parameter or something? We got more than one network, and surely others will follow in our footsteps as soon as they see the delicious eye candy.

We want to generate programmatically for production use. And have holodex consume the output of an API rather than github files, but we can wait on that.

Re source and target: I don't see the relationships duplicated from both the source and target sides. Looks like they are only recorded from the source side. Did I miss something?

(We don't care, by the way. We record the relationships in their own table, with links to the agents on both ends. But we are happy to conform to what holodex wants, in order to get that snazzy UI.)

**Comment by ahdinosaur** [comment]
> Can you host an instance that different networks could plug into by means of a query parameter or something? We got more than one network, and surely others will follow in our footsteps as soon as they see the delicious eye candy.

it's possible we fit everyone onto a single instance (allowing for multiple sources of data), or we make it easy to host multiple instances. we'll see what makes the most sense when it happens.

> Re source and target: I don't see the relationships duplicated from both the source and target sides. Looks like they are only recorded from the source side. Did I miss something?

the YAML might be confusing, but basically the data is a flat list of typed objects. in the YAML, any nesting is flattened (and [maybe a foreign key added](https://github.com/holodex/app/blob/master/src/node_modules/api/index.js#L87-L94)) when it's read.

**Comment by bhaugen** [comment]
That didn't answer my question about how Holodex wants relationships to be recorded in YAML.

Here's an excerpt of mj-kaplan.yml:

```
'@type': Person
name: MJ
me: &me
  agent: people/mj-kaplan

relationships:
  - '@type': Relationship
    type: relationshipTypes/stewardship
    context: groups/loomio
    roles:
      - '@type': Role
        type: roleTypes/steward
        <<: *me 
      - '@type': Role
        type: roleTypes/stewardee
        agent: people/matthew-bartlett
```

That same relationship does not appear in matthew-bartlet.yml (the stewardee). Instead, I see this other relationship where Matthew is the steward.

```
'@type': Person
name: Matthew Bartlett
me: &me
  agent: people/matthew-bartlett

relationships:
  - '@type': Relationship
    type: relationshipTypes/stewardship
    context: groups/loomio
    roles:
      - '@type': Role
        type: roleTypes/steward
        <<: *me 
      - '@type': Role
        type: roleTypes/stewardee
        agent: people/jon
```

In other words, it looks to me like you are recording each relationship once, in the yml file for the source. Correct? Or am I still missing something?

**Comment by simontegg** [comment]
That's correct. It only needs to be recorded once (at this stage).

**Comment by bhaugen** [comment]
Thanks, got it. Can do.

**Comment by bhaugen** [comment]
LinkTypes: some relationshipTypes have one, some have two. What's the difference?

set.yml:

```
links:
  - '@type': LinkType
    source: subgroup
    target: parent-group
    label: "are part of {target}"
```

membership.yml:

```
links:
  - '@type': LinkType
    source: member
    target: group
    label: "belong to {target}"
  - '@type': LinkType
    source: group
    target: member
    label: "include {target}"
```
